<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-2STQO06D" failures="1" tests="6" name="Default test" time="0.038" errors="0" timestamp="2021-10-16T20:15:28 IST">
  <testcase classname="Test.TestCalculate" name="emptyStringReturnsZero" time="0.005"/>
  <testcase classname="Test.TestCalculate" name="negativeInputReturnsException" time="0.001">
    <failure type="org.testng.TestException" message="
Method TestCalculate.negativeInputReturnsException()[pri:0, instance:Test.TestCalculate@693fe6c9] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method TestCalculate.negativeInputReturnsException()[pri:0, instance:Test.TestCalculate@693fe6c9] should have thrown an exception of type class java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- negativeInputReturnsException -->
  <testcase classname="Test.TestCalculate" name="singleValueIsReplied" time="0.001"/>
  <testcase classname="Test.TestCalculate" name="threeNumbersDelimitedBothWaysReturnsSum" time="0.001"/>
  <testcase classname="Test.TestCalculate" name="twoNumbersCommaDelimitedReturnsSum" time="0.0"/>
  <testcase classname="Test.TestCalculate" name="twoNumbersNewLineDelimitedReturnsSum" time="0.001"/>
</testsuite> <!-- Default test -->
